package com.example.bottomnavigation.harrychiong

import android.app.Activity
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Button
import android.widget.Toast
import androidx.fragment.app.DialogFragment
import com.example.bottomnavigation.R
import java.io.File


class PopUpFragment : DialogFragment() {

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {

        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_pop_up, container, false)
    }


    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        val btn1 = view.findViewById<Button>(R.id.btn_selectFile)
        val btn2 = view.findViewById<Button>(R.id.btn_submit)

        //Press button and go to file manager select file
        btn1.setOnClickListener {
            showFileChooser()
        }

        btn2.setOnClickListener() {
            Toast.makeText(context, "Submitted", Toast.LENGTH_LONG).show()
            // Create an email intent with recipient, subject, and body
            val recipient = "example@example.com"
            val subject = "Auto-generated email"
            val body = "This email was auto-generated by my app."
            val emailIntent = Intent(Intent.ACTION_SENDTO).apply {
                data = Uri.parse("mailto:")
                putExtra(Intent.EXTRA_EMAIL, arrayOf(recipient))
                putExtra(Intent.EXTRA_SUBJECT, subject)
                putExtra(Intent.EXTRA_TEXT, body)
            }

            // Launch the email app with the intent
            startActivity(Intent.createChooser(emailIntent, "Send email..."))
            dismiss()
        }

    }

    //this is a button after press it will go user's phone file manager to select the file and submit it
    private fun showFileChooser() {
        val intent = Intent(Intent.ACTION_GET_CONTENT)
        intent.type = "*/*"
        intent.addCategory(Intent.CATEGORY_OPENABLE)
        try {
            startActivityForResult(Intent.createChooser(intent, "Select a file"), 100)
            var REQUEST_CODE_FILE_PICKER = 100
            startActivityForResult(intent, REQUEST_CODE_FILE_PICKER)
        } catch (exception: Exception) {
            Toast.makeText(context, "Please install a file manager. ", Toast.LENGTH_SHORT).show()
        }

    }

    /*
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        var REQUEST_CODE_FILE_PICKER = 100
        if (requestCode == REQUEST_CODE_FILE_PICKER && resultCode == Activity.RESULT_OK) {
            val selectedFileUri = data?.data

            if (selectedFileUri != null) {
                val selectedFile = File(selectedFileUri.path)

            }

        }

    }

     */
}